import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Intel Codex Sidebar Configuration
 *
 * This sidebar is for the intel-codex vault content,
 * which is synced from the Obsidian vault via the obsidian-vault-plugin.
 *
 * The sidebar is auto-generated from the intel-codex folder structure,
 * which includes investigations, security analysis, pentesting, and case studies.
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from the intel-codex directory structure
  intelCodexSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
